apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dotnet-core
spec:
  selector:
    matchLabels:
      app: hello-dotnet-core
  replicas: 1 
  template: 
    metadata:
      labels:
        app: hello-dotnet-core
    spec:
      containers:
      - name: hello-dotnet-core
        image: naturalorder/fromharness:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: hello-dotnet-core
spec:
 type: NodePort
 selector:
   app: hello-dotnet-core
 ports:
   - name: client
     protocol: TCP
     port: 80
     nodePort: 32080
 selector:
   app: hello-dotnet-core
