
services:
  helloworlddotnetcore:
    image: helloworlddotnetcore
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - configuration=Debug
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
