pipeline:
  identifier: Build_Natural0rder_hello_dotnet_core_1743110282988
  name: Build hello-dotnet-core
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Natural0rder/hello-dotnet-core
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  identifier: build_dotnet_app
                  name: Build DotNet App
                  spec:
                    shell: Sh
                    command: |-
                      echo "Welcome to Harness CI"
                      dotnet restore
                      dotnet build hello-dotnet-core --no-restore
                      dotnet test --no-build --verbosity normal
              - step:
                  name: PushToDockerHub-FromTemplate
                  identifier: PushToDockerHubFromTemplate
                  template:
                    templateRef: BuildAndPushToDockerHub
                    versionLabel: Version1
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
